<?php
$config=array();
$class='Configurator';
$template='fgs.php';
$script='configurator.php';
$config['title']='grids';
$config['system']=1;
$config['session']=array('mode','previous_mode');
$config['initial']=array('mode'=>'master','previous_mode'=>'');
$config['acl']=array('users'=>array(),'roles'=>array('programmer'));
$config['master']['controller']=array('form'=>true,'grid'=>true,'search'=>true,'dataset'=>false);
$config['master']['components']=array();
$config['master']['class']='Unit';
$config['master']['type']='master';
$config['master']['components']['form'] =array('class'=>'Form','sid'=>'grid','display'=>0,'renderer'=>'FgsFormView','hide'=>1);
$config['master']['components']['grid'] =array('class'=>'GridGrid','sid'=>'grids','display'=>1,'renderer'=>'FgsGridView','hide'=>0,'multimode_hide'=>0);
$config['master']['components']['search'] =array('class'=>'Search','sid'=>'GridSearch','display'=>1,'renderer'=>'FgsSearchView','hide'=>0);
$config['master']['session']=array('controller');
$config['master']['initial']=array();
$config['units']=array('master','column','add','attribute');
$config['column']['controller']=array('form'=>true,'grid'=>true,'search'=>false,'dataset'=>false);
$config['column']['components']=array();
$config['column']['class']='Unit';
$config['column']['type']='detail';
$config['column']['components']['form'] =array('class'=>'Form','sid'=>'Column','display'=>0,'renderer'=>'FgsFormView','hide'=>1);
$config['column']['components']['grid'] =array('class'=>'Grid','sid'=>'columns','display'=>1,'renderer'=>'FgsGridView','hide'=>0,'multimode_hide'=>0);
$config['column']['session']=array('controller');
$config['column']['initial']=array();
$config['add']['controller']=array('form'=>false,'grid'=>true,'search'=>false,'dataset'=>false);
$config['add']['components']=array();
$config['add']['class']='Unit';
$config['add']['type']='auxiliary';
$config['add']['components']['grid'] =array('class'=>'Grid','sid'=>'InitGrid','display'=>1,'renderer'=>'FgsGridView','hide'=>0,'multimode_hide'=>0);
$config['add']['session']=array('controller');
$config['add']['initial']=array();
$config['attribute']['controller']=array('form'=>true,'grid'=>false,'search'=>false,'dataset'=>false);
$config['attribute']['components']=array();
$config['attribute']['class']='Attribute';
$config['attribute']['type']='attribute';
$config['attribute']['components']['form'] =array('class'=>'Form','sid'=>'dummy','display'=>1,'renderer'=>'AttributeView','hide'=>0);
$config['attribute']['session']=array('controller','component');
$config['attribute']['initial']=array('component'=>'dummy');