<?php
$grid['InputForms']=array();
$selector['InputForms']=array('field'=>'select','renderer'=>'selector','view'=>"<input onclick=\"toggleRow(%1\$d)\" type=checkbox name=\"select[%1\$d]\" id=\"id_select_%1\$d\" value=\"%2\$s\">");
$grid['InputForms']['properties']=array('table'=>'fgs_form','system'=>1,'primary_key'=>array('form_sid'),'modal'=>0,'user_order'=>1,'user_pagesize'=>1,'user_offset'=>1,'inline_edit'=>0,'title'=>'forms','joins'=>array(),'save'=>array('form_table','form_system'),'sort'=>array('form_table'=>'form_table','form_sid'=>'form_sid','form_title'=>'form_title','form_type'=>'form_type','form_startmode'=>'form_startmode','form_system'=>'form_system'),'sort_prefix'=>array(),'sort_suffix'=>array(),'register'=>array('form_sid'=>'form_sid','form_system'=>'system'),'select'=>'t.form_sid,t.form_table,t.form_title,t.form_type,t.form_startmode,t.form_system','from'=>'fgs_form t ');
$grid['InputForms']['initial']=array('pagesize'=>30,'direction'=>'ASC','order'=>'form_sid','offset'=>0);
$grid['InputForms']['session']=array('pagesize','direction','order','offset','total','multimode_hide','display','hide','apk','adk');
$ra['InputForms']=array();
$ra['InputForms'][]=array('load'=>false,'action'=>'update','renderer'=>'RowAction','immediate'=>0,'view'=>'<a href="%3$s&amp;update=%1$d&amp;key=%2$s" class="icon_edit" title="Edit" ></a>');
$ra['InputForms'][]=array('load'=>false,'action'=>'remove','renderer'=>'RowAction','immediate'=>0,'view'=>'<a href="%3$s&amp;remove=%1$d&amp;key=%2$s" class="icon_delete" title="Remove" ></a>');
$ra['InputForms'][]=array('load'=>false,'action'=>'add','renderer'=>'RowAction','immediate'=>0,'view'=>'<a href="%3$s&amp;add=%1$d&amp;key=%2$s" class="icon_add" title="Add" ></a>');
$ra['InputForms'][]=array('load'=>false,'action'=>'element','renderer'=>'RowAction','immediate'=>0,'view'=>'<a href="%3$s&amp;element=%1$d&amp;key=%2$s" class="icon_details" title="Element" ></a>');
$ra['InputForms'][]=array('load'=>false,'action'=>'validator','renderer'=>'RowAction','immediate'=>0,'view'=>'<a href="%3$s&amp;validator=%1$d&amp;key=%2$s" class="icon_validator" title="Validator" ></a>');
$ra['InputForms'][]=array('load'=>false,'action'=>'filter','renderer'=>'RowAction','immediate'=>0,'view'=>'<a href="%3$s&amp;filter=%1$d&amp;key=%2$s" class="icon_filter" title="Filter" ></a>');
$ra['InputForms'][]=array('load'=>false,'action'=>'copy','renderer'=>'RowAction','immediate'=>0,'view'=>'<a href="%3$s&amp;copy=%1$d&amp;key=%2$s" class="icon_copy" title="Copy" ></a>');
$rsa['InputForms']=array();
$rsa['InputForms'][]=array('action'=>'multi_update','renderer'=>'RowSetAction','immediate'=>0,'view'=>'<button type="submit" name="multi_update"  title="Multi_update" ><span style="margin:0 -5px -3px -0px;" class="icon_edit"></span></button>');
$rsa['InputForms'][]=array('action'=>'multi_remove','renderer'=>'RowSetAction','immediate'=>0,'view'=>'<button type="submit" name="multi_remove"  title="Multi_remove" ><span style="margin:0 -5px -3px -0px;" class="icon_delete"></span></button>');
$column['InputForms']=array();
$column['InputForms'][0]=array('rowid'=>217,'save'=>'1','component'=>'ColumnText','header'=>'Table','sid'=>'form_table','hidden'=>'0','renderer'=>'text','type'=>'varchar','field'=>'form_table','hidden'=>'0','calculate'=>'0');
$column['InputForms'][1]=array('rowid'=>218,'register'=>'form_sid','component'=>'ColumnText','header'=>'Sid','sid'=>'form_sid','hidden'=>'0','renderer'=>'text','type'=>'varchar','field'=>'form_sid','hidden'=>'0','calculate'=>'0');
$column['InputForms'][2]=array('rowid'=>219,'component'=>'ColumnText','header'=>'Title','sid'=>'form_title','hidden'=>'0','renderer'=>'text','type'=>'varchar','field'=>'form_title','hidden'=>'0','calculate'=>'0');
$column['InputForms'][3]=array('rowid'=>221,'component'=>'ColumnLookup','header'=>'Type','sid'=>'form_type','hidden'=>'0','join_lookup'=>0,'relation'=>'0','list'=>array('options'=>array('application'=>'application','template'=>'template','element'=>'element','predicate'=>'predicate','column'=>'column','system'=>'system')),'field'=>'form_type','hidden'=>'0','type'=>'varchar','align'=>'left','list_sid'=>'FormType','renderer'=>'option');
$column['InputForms'][4]=array('rowid'=>5766,'component'=>'ColumnText','header'=>'Start mode','sid'=>'form_startmode','hidden'=>'0','renderer'=>'text','type'=>'varchar','field'=>'form_startmode','hidden'=>'0','calculate'=>'0');
$column['InputForms'][5]=array('rowid'=>5698,'save'=>'1','register'=>'system','component'=>'ColumnLookup','header'=>'System ?','sid'=>'form_system','hidden'=>'0','join_lookup'=>0,'relation'=>'0','list'=>array('options'=>array('0'=>'no','1'=>'yes')),'field'=>'form_system','hidden'=>'0','type'=>'tinyint','list_sid'=>'YesNo','renderer'=>'option');
$button['InputForms']=array();