<?php
$grid['options']=array();
$selector['options']=array('field'=>'selectrow','renderer'=>'selector','view'=>"<input onclick=\"toggleRow(%1\$d)\" type=checkbox name=\"selectrow[%1\$d]\" id=\"id_selectrow_%1\$d\" value=\"%2\$s\">");
$grid['options']['properties']=array('table'=>'fgs_option','system'=>1,'primary_key'=>array('option_list','option_sid'),'modal'=>0,'user_order'=>1,'user_pagesize'=>1,'user_offset'=>1,'inline_edit'=>0,'fkr'=>array('option_list'=>'list_sid'),'title'=>'list_options','joins'=>array(),'save'=>array(),'sort'=>array('option_list'=>'option_list','option_sid'=>'option_sid','option_en'=>'option_en','option_ru'=>'option_ru','option_index'=>'option_index'),'sort_prefix'=>array('option_index'=>'option_list'),'sort_suffix'=>array('option_list'=>'option_index ASC'),'register'=>array(),'select'=>'t.option_list,option_sid,t.option_list,t.option_sid,t.option_en,t.option_ru,t.option_index','from'=>'fgs_option t ');
$grid['options']['initial']=array('pagesize'=>30,'direction'=>'ASC','order'=>'option_list','offset'=>0);
$grid['options']['session']=array('pagesize','direction','order','offset','total','multimode_hide','display','hide','apk','foreign_key');
$ra['options']=array();
$ra['options'][]=array('load'=>false,'action'=>'update','renderer'=>'RowAction','immediate'=>0,'view'=>'<a href="%3$s&amp;update=%1$d&amp;key=%2$s" class="icon_edit" title="Edit" ></a>');
$ra['options'][]=array('load'=>false,'action'=>'remove','renderer'=>'RowAction','immediate'=>0,'view'=>'<a href="%3$s&amp;remove=%1$d&amp;key=%2$s" class="icon_delete" title="Remove" ></a>');
$ra['options'][]=array('load'=>false,'action'=>'copy','renderer'=>'RowAction','immediate'=>0,'view'=>'<a href="%3$s&amp;copy=%1$d&amp;key=%2$s" class="icon_copy" title="Copy" ></a>');
$rsa['options']=array();
$rsa['options'][]=array('action'=>'multi_update','renderer'=>'RowSetAction','immediate'=>0,'view'=>'<button type="submit" name="multi_update"  title="Multi_update" ><span style="margin:0 -5px -3px -0px;" class="icon_edit"></span></button>');
$rsa['options'][]=array('action'=>'multi_remove','renderer'=>'RowSetAction','immediate'=>0,'view'=>'<button type="submit" name="multi_remove"  title="Multi_remove" ><span style="margin:0 -5px -3px -0px;" class="icon_delete"></span></button>');
$column['options']=array();
$column['options'][0]=array('rowid'=>5647,'component'=>'ColumnText','header'=>'List','sid'=>'option_list','hidden'=>'0','renderer'=>'text','type'=>'varchar','field'=>'option_list','hidden'=>'0','calculate'=>'0','align'=>'left');
$column['options'][1]=array('rowid'=>5646,'component'=>'ColumnText','header'=>'Sid','sid'=>'option_sid','hidden'=>'0','renderer'=>'text','type'=>'varchar','field'=>'option_sid','hidden'=>'0','calculate'=>'0');
$column['options'][2]=array('rowid'=>5645,'component'=>'ColumnText','header'=>'Option in English','sid'=>'option_en','hidden'=>'0','renderer'=>'text','type'=>'varchar','field'=>'option_en','hidden'=>'0','calculate'=>'0');
$column['options'][3]=array('rowid'=>5644,'component'=>'ColumnText','header'=>'Option in russian','sid'=>'option_ru','hidden'=>'0','renderer'=>'text','type'=>'varchar','field'=>'option_ru','hidden'=>'0','calculate'=>'0');
$column['options'][4]=array('rowid'=>5643,'component'=>'ColumnText','header'=>'Index','sid'=>'option_index','hidden'=>'0','renderer'=>'text','type'=>'int','field'=>'option_index','hidden'=>'0','calculate'=>'0');
$button['options']=array();