<?php
$form['authentification']=array();
$form['authentification']['initial']=array();
$form['authentification']['session']['seek']=array('mode','hide','display','apk');
$button['authentification']=array();
$button['authentification'][]=array('file'=>'enter.jpg','value'=>'Логин','name'=>'seek','renderer'=>'button','type'=>'submit','action'=>'seek','modes'=>array('seek'));
$form['authentification']['properties']=array('primary_key'=>array('user_rowid'),'table'=>'fgs_user','method'=>'post','system'=>1,'modes'=>array('seek'),'system'=>1,'title'=>'authentification','modes'=>array('seek'),'id'=>'user','attributes'=>"",'htmlevents'=>"",'enctype'=>'application/x-www-form-urlencoded','events'=>array('seek'=>'found'),'joins'=>array());
$e['authentification']=array();
$e['authentification'][0]=array('table'=>'fgs_user','rowid'=>'3413','sid'=>'user_login','fieldset'=>'','name'=>'username','label'=>'Логин','component'=>'InputText','type'=>'varchar','required'=>1,'name'=>'username','modes'=>array('seek'),'field'=>'user_login','renderer'=>'text','cai'=>'1','attributes'=>"maxlength='128' size='20'");
$e['authentification'][1]=array('table'=>'fgs_user','rowid'=>'3414','sid'=>'user_password','fieldset'=>'','name'=>'password','label'=>'Пароль','component'=>'InputSecret','renderer'=>'secret','field'=>'user_password','required'=>1,'name'=>'password','modes'=>array('seek'),'type'=>'varchar','attributes'=>"maxlength='20' size='20'");
$e['authentification'][2]=array('table'=>'fgs_user','rowid'=>'11388','sid'=>'user_country','fieldset'=>'','name'=>'user_country','label'=>'Страна','trim'=>'trim','component'=>'InputText','hidden'=>1,'type'=>'char','required'=>1,'modes'=>array('seek'),'field'=>'user_country','renderer'=>'text','cai'=>'1');
$e['authentification'][3]=array('table'=>'fgs_user','rowid'=>'11389','sid'=>'user_email','fieldset'=>'','name'=>'user_email','label'=>'E-mail','trim'=>'trim','component'=>'InputText','hidden'=>1,'type'=>'varchar','required'=>1,'modes'=>array('seek'),'field'=>'user_email','renderer'=>'text','cai'=>'1','attributes'=>"maxlength='128' size='60'");
$e['authentification'][4]=array('table'=>'fgs_user','rowid'=>'11390','sid'=>'user_language','fieldset'=>'','name'=>'user_language','label'=>'User_language','trim'=>'trim','component'=>'InputText','hidden'=>1,'type'=>'varchar','modes'=>array('seek'),'field'=>'user_language','renderer'=>'text','cai'=>'1','attributes'=>"maxlength='64' size='60'");
$e['authentification'][5]=array('table'=>'fgs_user','rowid'=>'11391','sid'=>'user_lastname','fieldset'=>'','name'=>'user_lastname','label'=>'Фамилия','trim'=>'trim','component'=>'InputText','hidden'=>1,'type'=>'varchar','required'=>1,'modes'=>array('seek'),'field'=>'user_lastname','renderer'=>'text','cai'=>'1','attributes'=>"maxlength='64' size='60'");
$e['authentification'][6]=array('table'=>'fgs_user','rowid'=>'11392','sid'=>'user_role','fieldset'=>'','name'=>'user_role','label'=>'Роль','trim'=>'trim','component'=>'InputText','hidden'=>1,'type'=>'varchar','required'=>1,'modes'=>array('seek'),'field'=>'user_role','renderer'=>'text','cai'=>'1');
$e['authentification'][7]=array('table'=>'fgs_user','rowid'=>'11393','sid'=>'user_secondname','fieldset'=>'','name'=>'user_secondname','label'=>'Отчество','trim'=>'trim','component'=>'InputText','hidden'=>1,'type'=>'varchar','modes'=>array('seek'),'field'=>'user_secondname','renderer'=>'text','cai'=>'1','attributes'=>"maxlength='64' size='60'");
$e['authentification'][8]=array('table'=>'fgs_user','rowid'=>'11394','sid'=>'user_title','fieldset'=>'','name'=>'user_title','label'=>'Название','trim'=>'trim','component'=>'InputText','hidden'=>1,'type'=>'varchar','required'=>1,'modes'=>array('seek'),'field'=>'user_title','renderer'=>'text','cai'=>'1');