<?php
$form['list_option']=array();
$form['list_option']['initial']=array();
$form['list_option']['initial']=array('mode'=>'insert');
$form['list_option']['session']['insert']=array('mode','hide','display','amf','foreign_key');
$form['list_option']['session']['copy']=array('mode','hide','display','apk','irow','amf','foreign_key');
$form['list_option']['session']['read']=array('mode','hide','display','apk','irow','amf','foreign_key');
$form['list_option']['session']['update']=array('mode','hide','display','apk','irow','amf','foreign_key');
$form['list_option']['session']['remove']=array('mode','hide','display','apk','irow','amf','foreign_key');
$form['list_option']['session']['multi_update']=array('mode','hide','display','apk','irow','amf','foreign_key');
$form['list_option']['session']['multi_remove']=array('mode','hide','display','apk','irow','amf','foreign_key');
$form['list_option']['session']['multi_read']=array('mode','hide','display','apk','irow','amf','foreign_key');
$button['list_option']=array();
$button['list_option'][]=array('value'=>'Вставить','name'=>'insert','renderer'=>'button','type'=>'submit','action'=>'insert','modes'=>array('insert','copy'),'attributes'=>'tabindex=\'0\'');
$button['list_option'][]=array('value'=>'Обновить','name'=>'update','renderer'=>'button','type'=>'submit','action'=>'update','modes'=>array('update','multi_update'),'attributes'=>'tabindex=\'0\'');
$button['list_option'][]=array('value'=>'Удалить','name'=>'remove','renderer'=>'button','type'=>'submit','action'=>'remove','modes'=>array('remove','multi_remove'),'attributes'=>'tabindex=\'0\'');
$button['list_option'][]=array('value'=>'Read','name'=>'read','renderer'=>'button','type'=>'submit','action'=>'read','modes'=>array('multi_read'),'attributes'=>'tabindex=\'0\'');
$button['list_option'][]=array('value'=>'Отменить','name'=>'cancel','renderer'=>'button','type'=>'submit','action'=>'cancel','modes'=>array('insert','update','copy','remove','read','multi_update','multi_remove','multi_read'),'attributes'=>'tabindex=\'0\'');
$button['list_option'][]=array('value'=>'Отменить изменения','name'=>'reset','renderer'=>'button','type'=>'reset','action'=>'reset','modes'=>array('insert','update','copy','multi_update'),'attributes'=>'tabindex=\'0\'');
$form['list_option']['properties']=array('primary_key'=>array('option_list','option_sid'),'table'=>'fgs_option','method'=>'post','system'=>1,'redirect_after_insert'=>0,'modes'=>array('insert','update','copy','remove','read','multi_update','multi_remove','multi_read'),'system'=>1,'title'=>'list_option','modes'=>array('insert','update','copy','remove','read','multi_update','multi_remove','multi_read'),'attributes'=>'','htmlevents'=>'','enctype'=>'application/x-www-form-urlencoded','events'=>array('insert'=>'done','update'=>'done','remove'=>'done'),'joins'=>array());
$e['list_option']=array();
$e['list_option'][0]=array('table'=>'fgs_option','rowid'=>'10436','sid'=>'option_list','fieldset'=>'','name'=>'option_list','label'=>'Список','component'=>'InputForeignKey','foreign_key'=>'list_sid','hidden'=>1,'type'=>'varchar','field'=>'option_list','modes'=>array('insert','update','copy','remove','read','multi_update','multi_remove','multi_read'));
$e['list_option'][1]=array('table'=>'fgs_option','rowid'=>'10435','sid'=>'option_sid','fieldset'=>'','name'=>'option_sid','label'=>'Sid','component'=>'InputText','type'=>'text','required'=>1,'modes'=>array('insert','update','copy','remove','multi_update','multi_remove'),'field'=>'option_sid','renderer'=>'text','cai'=>'1','attributes'=>'maxlength=\'64\' size=\'60\'');
$e['list_option'][2]=array('table'=>'fgs_option','rowid'=>'10437','sid'=>'option_en','fieldset'=>'','name'=>'option_en','label'=>'Опция на английском','component'=>'InputText','type'=>'varchar','required'=>1,'modes'=>array('insert','update','copy','remove','read','multi_update','multi_remove','multi_read'),'field'=>'option_en','renderer'=>'text','cai'=>'1','attributes'=>'maxlength=\'255\' size=\'60\'');
$e['list_option'][3]=array('table'=>'fgs_option','rowid'=>'10439','sid'=>'option_ru','fieldset'=>'','name'=>'option_ru','label'=>'Опция на русском','component'=>'InputText','type'=>'varchar','required'=>1,'modes'=>array('insert','update','copy','remove','read','multi_update','multi_remove','multi_read'),'field'=>'option_ru','renderer'=>'text','cai'=>'1','attributes'=>'maxlength=\'255\' size=\'60\'');
$e['list_option'][4]=array('table'=>'fgs_option','rowid'=>'10438','sid'=>'option_index','fieldset'=>'','name'=>'option_index','label'=>'Индекс','component'=>'InputText','type'=>'int','required'=>1,'default_value'=>'0','modes'=>array('insert','update','copy','remove','read','multi_update','multi_remove','multi_read'),'field'=>'option_index','renderer'=>'text','cai'=>'1','attributes'=>'maxlength=\'10\' size=\'10\'');
$e['list_option'][5]=array('table'=>'fgs_option','rowid'=>'10440','sid'=>'option_system','fieldset'=>'','name'=>'option_system','label'=>'System ?','default_value'=>'&rgv system','component'=>'InputSystem','hidden'=>1,'modes'=>array('insert','update','copy','remove','read','multi_update','multi_remove','multi_read'),'field'=>'option_system','cai'=>0);