<?php
$item[0]["type"]="menu";
$item[0]["name"]="Спецификация";
$item[0]["class"]="top_parent";
$item[0]["child_nodes"]=array(1,2,3,4,5,6,7,8,9,10,11,12);
$item[1]["type"]="item";
$item[1]["name"]="Форма ввода";
$item[1]["url"]="configurator.php?fgsc=forms&fgsw=forms";
$item[1]["pid"]="1000";
$item[2]["type"]="item";
$item[2]["name"]="Грид";
$item[2]["url"]="configurator.php?fgsc=grids&fgsw=grids";
$item[2]["pid"]="1000";
$item[3]["type"]="item";
$item[3]["name"]="Форма поиска";
$item[3]["url"]="configurator.php?fgsc=searchs&fgsw=searchs";
$item[3]["pid"]="1000";
$item[4]["type"]="item";
$item[4]["name"]="Контроллер";
$item[4]["url"]="configurator.php?fgsc=controllers&fgsw=controllers";
$item[4]["pid"]="1000";
$item[5]["type"]="item";
$item[5]["name"]="Набор данных";
$item[5]["url"]="configurator.php?fgsc=datasets&fgsw=datasets";
$item[5]["pid"]="1000";
$item[6]["type"]="item";
$item[6]["name"]="Список";
$item[6]["url"]="configurator.php?fgsc=lists&fgsw=lists";
$item[6]["pid"]="1000";
$item[7]["type"]="item";
$item[7]["name"]="Опция списка";
$item[7]["url"]="configurator.php?fgsc=options&fgsw=options";
$item[7]["pid"]="1000";
$item[8]["type"]="item";
$item[8]["name"]="Условие";
$item[8]["url"]="configurator.php?fgsc=condition&fgsw=condition";
$item[8]["pid"]="1000";
$item[9]["type"]="item";
$item[9]["name"]="Конвертер";
$item[9]["url"]="configurator.php?fgsc=converter&fgsw=converter";
$item[9]["pid"]="1000";
$item[10]["type"]="item";
$item[10]["name"]="Поле таблицы";
$item[10]["url"]="configurator.php?fgsc=fieldsSpecification&fgsw=fieldsSpecification";
$item[10]["pid"]="1000";
$item[11]["type"]="item";
$item[11]["name"]="Меню";
$item[11]["url"]="configurator.php?fgsc=menus&fgsw=menus";
$item[11]["pid"]="1000";
$item[12]["type"]="item";
$item[12]["name"]="Импорт схемы БД";
$item[12]["url"]="dbload.php";
$item[12]["pid"]="1000";
$item[13]["type"]="menu";
$item[13]["name"]="Системная таблица";
$item[13]["class"]="top_parent";
$item[13]["child_nodes"]=array(14,15,16,17,18);
$item[14]["type"]="item";
$item[14]["name"]="Сообщение";
$item[14]["url"]="configurator.php?fgsc=messages&fgsw=messages";
$item[14]["pid"]="1090";
$item[15]["type"]="item";
$item[15]["name"]="Роль пользователя";
$item[15]["url"]="configurator.php?fgsc=user_roles&fgsw=user_roles";
$item[15]["pid"]="1090";
$item[16]["type"]="item";
$item[16]["name"]="Таблица";
$item[16]["url"]="configurator.php?fgsc=table&fgsw=tables";
$item[16]["pid"]="1090";
$item[17]["type"]="item";
$item[17]["name"]="Параметер";
$item[17]["url"]="configurator.php?fgsc=parameters&fgsw=parameters";
$item[17]["pid"]="1090";
$item[18]["type"]="item";
$item[18]["name"]="Экспорт";
$item[18]["url"]="configurator.php?fgsc=export&fgsw=export";
$item[18]["pid"]="1090";
$item[19]["type"]="menu";
$item[19]["name"]="Экспорт";
$item[19]["class"]="top_parent";
$item[19]["child_nodes"]=array(20,21,22,23,24,25,26,27);
$item[20]["type"]="item";
$item[20]["name"]="Список";
$item[20]["url"]="export.php?component=list";
$item[20]["pid"]="1099";
$item[21]["type"]="item";
$item[21]["name"]="Форма ввода";
$item[21]["url"]="export.php?component=form";
$item[21]["pid"]="1099";
$item[22]["type"]="item";
$item[22]["name"]="Форма поиска";
$item[22]["url"]="export.php?component=search";
$item[22]["pid"]="1099";
$item[23]["type"]="item";
$item[23]["name"]="Грид";
$item[23]["url"]="export.php?component=grid";
$item[23]["pid"]="1099";
$item[24]["type"]="item";
$item[24]["name"]="Набор данных";
$item[24]["url"]="export.php?component=dataset";
$item[24]["pid"]="1099";
$item[25]["type"]="item";
$item[25]["name"]="Контроллер";
$item[25]["url"]="export.php?component=controller";
$item[25]["pid"]="1099";
$item[26]["type"]="item";
$item[26]["name"]="Меню";
$item[26]["url"]="export.php?component=menu";
$item[26]["pid"]="1099";
$item[27]["type"]="item";
$item[27]["name"]="Сообщение";
$item[27]["url"]="export.php?component=message";
$item[27]["pid"]="1099";
?>