<?php
$item[0]["type"]="item";
$item[0]["name"]="Главная страница";
$item[0]["url"]="index.php";
$item[1]["type"]="menu";
$item[1]["name"]="Documentation";
$item[1]["url"]="documentation.php";
$item[1]["child_nodes"]=array(2,3,4);
$item[2]["type"]="item";
$item[2]["name"]="Введение";
$item[2]["url"]="documentation.php?fgsdoc=fgstools";
$item[2]["pid"]="42000";
$item[3]["type"]="item";
$item[3]["name"]="Фреймворк";
$item[3]["url"]="documentation.php?fgsdoc=framework";
$item[3]["pid"]="42000";
$item[4]["type"]="item";
$item[4]["name"]="Конфигуратор";
$item[4]["url"]="documentation.php?fgsdoc=configurator";
$item[4]["pid"]="42000";
$item[5]["type"]="item";
$item[5]["name"]="Конфигуратор";
$item[5]["url"]="configurator.php";
?>